config/routes.rb
Rails.application.routes.draw do
  root 'landing#index'

  # Error routes that work in conjunction with
  # config.exceptions_app = self.routes.
  match '/404', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

  ######################### Public website routes ###########################

  resources :agents, only: :show do
    match '/items', to: 'agents#items', via: :get, as: 'items'
  end
  match '/auth/:provider/callback', to: 'sessions#create', via: [:get, :post],
        as: 'auth' # used by omniauth
  resources :binaries, only: :show do
    match '/object', to: 'binaries#object', via: :get
    match '/stream', to: 'binaries#stream', via: :get
  end
  match '/collections/iiif', to: 'collections#iiif_presentation_list',
        via: :get, as: 'collections_iiif_presentation_list',
        defaults: { format: :json }
  resources :collections, only: [:index, :show] do
    match 'items/treedata', to: 'items#tree_data', via: [:get, :post]
    match 'tree', to: 'items#tree', via: :get
    resources :items, only: :index
    # IIIF Presentation API 2.1 routes
    match '/iiif', to: 'collections#iiif_presentation', via: :get,
          as: 'iiif_presentation', defaults: { format: :json }
  end
  resources :downloads, only: :show, param: :key do
    match '/file', to: 'downloads#file', via: :get, as: 'file'
  end
  match '/health', to: 'health#index', via: :get
  resources :items, only: [:index, :show] do
    match '/treedata', to: 'items#item_tree_node', via: [:get, :post]
    match '/binaries/:filename', to: 'items#binary', via: :get, as: 'binary'
    match '/files', to: 'items#files', via: :get, as: 'files'
    # IIIF Presentation API 2.1 routes
    match '/annotation/:name', to: 'items#iiif_image_resource', via: :get,
          as: 'iiif_image_resource', defaults: { format: :json }
    match '/canvas/:id', to: 'items#iiif_canvas', via: :get, as: 'iiif_canvas',
          defaults: { format: :json }
    match '/layer/:name', to: 'items#iiif_layer', via: :get, as: 'iiif_layer',
          defaults: { format: :json }
    match '/annotation-list/:name', to: 'items#iiif_annotation_list', via: :get,
          as: 'iiif_annotation_list',
          defaults: { format: :json }
    match '/manifest', to: 'items#iiif_manifest', via: :get,
          as: 'iiif_manifest', defaults: { format: :json }
    match '/range/:name', to: 'items#iiif_range', via: :get, as: 'iiif_range',
          defaults: { format: :json }
    match '/sequence/:name', to: 'items#iiif_sequence', via: :get,
          as: 'iiif_sequence', defaults: { format: :json }
    # IIIF Search API routes
    match '/manifest/search', to: 'items#iiif_search', via: :get,
          as: 'iiif_search', defaults: { format: :json }
    # Wellcome Library API extension
    match '/xsequence/:name', to: 'items#iiif_media_sequence', via: :get,
          as: 'iiif_media_sequence', defaults: { format: :json }
  end
  match '/oai-pmh', to: 'oai_pmh#handle', via: %w(get post), as: 'oai_pmh'
  match '/oai-pmh/idhh', to: 'oai_pmh#handle', via: %w(get post), as: 'idhh_oai_pmh'
  match '/oai-pmh/primo', to: 'oai_pmh#handle', via: %w(get post), as: 'primo_oai_pmh'
  match '/search', to: redirect('/', status: 301), via: :all
  match '/signin', to: 'sessions#new', via: :get
  match '/signout', to: 'sessions#destroy', via: :delete

  ######################### Control Panel routes ###########################

  namespace :admin do
    root 'dashboard#index'

    resources :agents
    resources :agent_relation_types, except: :show,
              path: 'agent-relation-types'
    resources :agent_relations, except: [:index, :show], path: 'agent-relations'
    resources :agent_rules, except: :show, path: 'agent-rules'
    resources :agent_types, except: :show, path: 'agent-types'
    resources :binaries, only: :update do
      match '/edit-access', to: 'binaries#edit_access', via: :get
      match '/run-ocr', to: 'binaries#run_ocr', via: :patch
    end
    match '/collections/items', to: 'collections#items', via: :get
    match '/collections/sync', to: 'collections#sync', via: :patch,
          as: 'collections_sync'
    resources :collections, except: [:edit, :new, :create, :delete] do
      match '/edit-access', to: 'collections#edit_access', via: :get,
            constraints: lambda { |request| request.xhr? }
      match '/edit-email-watchers', to: 'collections#edit_email_watchers', via: :get,
            constraints: lambda { |request| request.xhr? }
      match '/edit-info', to: 'collections#edit_info', via: :get,
            constraints: lambda { |request| request.xhr? }
      match '/edit-representation', to: 'collections#edit_representation', via: :get,
            constraints: lambda { |request| request.xhr? }
      resources :item_sets, except: :index do
        match '/all-items', to: 'item_sets#remove_all_items', via: :delete , as: "remove_all_items"
        match '/items', to: 'item_sets#items', via: :get, as: "items"
        match '/items', to: 'item_sets#remove_items', via: :delete, as: "remove_items"
      end
      match '/items/edit', to: 'items#edit_all', via: :get
      match '/items/enable-full-text-search', to: 'items#enable_full_text_search',
            via: :patch
      match '/items/disable-full-text-search', to: 'items#disable_full_text_search',
            via: :patch
      match '/items', to: 'collections#delete_items', via: :delete,
            as: 'delete_items'
      match '/items/publish', to: 'items#publish', via: :patch
      match '/items/run-ocr', to: 'items#run_ocr', via: :patch
      match '/items/unpublish', to: 'items#unpublish', via: :patch
      match '/items/update', to: 'items#update_all', via: :post
      resources :items, except: :edit do
        match '/edit-access', to: 'items#edit_access', via: :get,
              constraints: lambda { |request| request.xhr? }
        match '/edit-info', to: 'items#edit_info', via: :get,
              constraints: lambda { |request| request.xhr? }
        match '/edit-metadata', to: 'items#edit_metadata', via: :get,
              constraints: lambda { |request| request.xhr? }
        match '/edit-representation', to: 'items#edit_representation', via: :get,
              constraints: lambda { |request| request.xhr? }
        match '/publicize-child-binaries', to: 'items#publicize_child_binaries',
              via: :post
        match '/purge-cached-images', to: 'items#purge_cached_images',
              via: :post
        match '/run-ocr', to: 'items#run_ocr', via: :patch
        match '/unpublicize-child-binaries', to: 'items#unpublicize_child_binaries',
              via: :post
      end
      match '/items/add-items-to-item-set', to: 'items#add_items_to_item_set',
            via: :post
      match '/items/add-query-to-item-set', to: 'items#add_query_to_item_set',
            via: :post
      match '/items/import', to: 'items#import', via: :post
      match '/items/import-embedded-file-metadata',
            to: 'items#import_embedded_file_metadata', via: :post
      match '/items/batch-change-metadata', to: 'items#batch_change_metadata',
            via: :post
      match '/items/migrate-metadata', to: 'items#migrate_metadata', via: :post
      match '/items/replace-metadata', to: 'items#replace_metadata', via: :post
      match '/items/sync', to: 'items#sync', via: :post
      match '/purge-cached-images', to: 'collections#purge_cached_images',
            via: :post
      match '/statistics', to: 'collections#statistics', via: :get
      match '/unwatch', to: 'collections#unwatch', via: :patch
      match '/watch', to: 'collections#watch', via: :patch
    end
    resources :elements, param: :name do
      match '/usages', to: 'elements#usages', via: :get
    end
    match '/elements/import', to: 'elements#import', via: :post,
          as: 'elements_import'
    resources :host_groups
    resources :metadata_profile_elements,
              only: [:create, :update, :destroy, :edit]
    resources :metadata_profiles, path: 'metadata-profiles' do
      match '/clone', to: 'metadata_profiles#clone', via: :patch, as: 'clone'
      match '/delete-elements', to: 'metadata_profiles#delete_elements',
            via: :post, as: 'delete_elements'
      match '/reindex-items', to: 'metadata_profiles#reindex_items',
            via: :post, as: 'reindex_items'
    end
    match '/metadata-profiles/import', to: 'metadata_profiles#import',
          via: :post, as: 'metadata_profile_import'
    match '/settings', to: 'settings#index', via: :get
    match '/settings', to: 'settings#update', via: :patch
    match '/statistics', to: 'statistics#index', via: :get
    resources :tasks
    resources :users, param: :username, except: [:edit, :update] do
      match '/reset-api-key', to: 'users#reset_api_key', via: :post, as: 'reset_api_key'
    end
    resources :vocabularies do
      resources :vocabulary_terms, path: "terms"
      match '/delete-vocabulary-terms',
            to: 'vocabularies#delete_vocabulary_terms',
            via: :post, as: 'delete_vocabulary_terms'
    end
    match '/vocabularies/import', to: 'vocabularies#import', via: :post,
          as: 'vocabulary_import'
  end

  ############################ REST API routes ##############################

  namespace :api do
    root 'landing#index'
    resources :collections, only: [:index, :show, :update] do
      resources :items, only: :index
    end
    resources :items, only: [:index, :show, :destroy]
    match '/items/:id', to: 'items#update', via: :put
  end

  namespace :harvest do
    root 'harvest#index'
    resources :agents, only: :show, defaults: { format: :json }
    resources :collections, only: :show, defaults: { format: :json }
    resources :items, only: :show, defaults: { format: :json }
  end

  ############# Redirects from images.library.uiuc/illinois.edu #############

  match '/projects/:alias', to: 'collections#show_contentdm', via: :get

app/controllers/api/collections_controller.rb
module Api

  class CollectionsController < ApiController

    ##
    # Responds to GET /api/collections
    #
    def index
      @start = params[:start].to_i
      @limit = params[:limit].to_i
      @limit = DEFAULT_RESULTS_LIMIT if @limit < 1
      @limit = MAX_RESULTS_LIMIT if @limit > MAX_RESULTS_LIMIT

      relation = Collection.search.
          aggregations(false).
          search_children(true).
          include_unpublished(true).
          include_restricted(true).
          facet_filters(params[:fq]).
          query_all(params[:q]).
          order(CollectionElement.new(name: 'title').indexed_sort_field).
          start(@start).
          limit(@limit)
      @count       = relation.count
      @collections = relation.to_a

      render json: {
          start: @start,
          limit: @limit,
          numResults: @count,
          results: @collections.to_a.map { |c|
            { title: c.title, id: c.repository_id, url: api_collection_url(c) }
          }
      }
    end

  end

end

app/controllers/collections_controller.rb
# frozen_string_literal: true

class CollectionsController < WebsiteController

  LOGGER                  = CustomLogger.new(CollectionsController)
  PERMITTED_SEARCH_PARAMS = [:fq, :id, :q]

  before_action :set_permitted_params, only: :show
  before_action :enable_cors, only: :iiif_presentation
  before_action :set_collection, only: [:iiif_presentation, :show]
  before_action :authorize_collection, only: [:iiif_presentation, :show]

  ##
  # Serves IIIF Presentation API 2.1 collections.
  #
  # Responds to `GET /collections/:id/iiif`
  #
  # @see http://iiif.io/api/presentation/2.1/#collection
  #
  def iiif_presentation
    render 'collections/iiif_presentation_api/collection',
           formats: :json,
           content_type: 'application/json'
  end

  ##
  # Serves an index of IIIF Presentation API collection representations.
  # N.B.: This endpoint is not an official part of the Presentation API.
  #
  # Responds to `GET /collections/iiif`
  #
  def iiif_presentation_list
    authorize(Collection)
    @collections = Collection.search.
        host_groups(client_host_groups).
        order(CollectionElement.new(name: 'title').indexed_sort_field)

    render 'collections/iiif_presentation_api/index',
           formats: :json,
           content_type: 'application/json'
  end

  ##
  # This is a legacy route that used to be served by this application, but now
  # the Metadata Gateway, or whatever it's called, serves it instead.
  #
  # Responds to `GET /collections`
  #
  def index
    authorize(Collection)
    redirect_to ::Configuration.instance.metadata_gateway_url + '/collections',
                status:           301,
                allow_other_host: true
  end

  ##
  # Responds to `GET /collections/:id`
  #
  # N.B.: Unpublished collections are allowed to be shown, but any items
  # residing in them are NOT.
  #
  def show
    @uofi_user = @collection.authorized_by_any_host_groups?(request_context.client_host_groups)
    respond_to do |format|
      format.html do
        @children = []
        if @uofi_user
          @children = Collection.search.
              search_children(true).
              parent_collection(@collection).
              order(CollectionElement.new(name: 'title').indexed_sort_field).
              to_a
          @num_public_objects = @collection.num_public_objects rescue nil
          if @collection.representation_type == Representation::Type::ITEM
            @representative_item = @collection.representative_item
          elsif @collection.representation_type == Representation::Type::MEDUSA_FILE
            bin = Binary.find_by_medusa_uuid(@collection.representative_medusa_file_id)
            @representative_item = bin.item if bin
          end
          # Show the "Browse Folder Tree" button only if the collection is
          # free-form and has no child items.
          @show_browse_tree_button = @collection.free_form? ?
                                         (@collection.items.where('parent_repository_id IS NOT NULL').count > 0) : false
        end
      end
      format.json do
        if @uofi_user
          render json: @collection.decorate
        else
          render plain: '403 Forbidden', status: :forbidden
        end
      end
    end
  end

  ##
  # Responds to `GET /projects/:alias`.
  #
  # This is a legacy route from `images.library.illinois.edu`.
  #
  def show_contentdm
    col = Collection.where('LOWER(contentdm_alias) = ?',
                           params[:alias].downcase).first
    raise ActiveRecord::RecordNotFound unless col
    redirect_to col
  end


  private

  def authorize_collection
    @collection ? authorize(@collection) : skip_authorization
  end

  def set_collection
    @collection = Collection.find_by_repository_id(params[:collection_id] || params[:id])
    raise ActiveRecord::RecordNotFound unless @collection
  end

  def set_permitted_params
    @permitted_params = params.permit(PERMITTED_SEARCH_PARAMS)
  end

end

app/controllers/harvest/collections_controller.rb
module Harvest

  class CollectionsController < AbstractHarvestController

    before_action :load_collection

    ##
    # Responds to `GET /harvest/collections/:id`
    #
    def show
      struct              = @collection.as_harvestable_json
      struct[:public_uri] = collection_url(@collection)
      parent              = @collection.parents.first
      struct[:parent]     = { id: parent.repository_id,
                              uri: collection_url(parent) } if parent
      render json: struct
    end

    private

    def load_collection
      @collection = Collection.find_by_repository_id(params[:id])
      raise ActiveRecord::RecordNotFound unless @collection
    end

  end

end

app/helpers/collections_helper.rb
module CollectionsHelper

  ##
  # @param collection [Collection]
  # @return [String] HTML string
  #
  def collection_page_title(collection)
    html = StringIO.new
    num_parents = collection.parents.count
    if num_parents > 0
      relative_parent = collection.parents.first
      html << '<h1 class="dl-title dl-compound-title">'
      html <<   '<small>'
      html <<     link_to(relative_parent.title, relative_parent)
      html <<   '</small>'
      html <<   '<br>'
      html <<   '&nbsp;&nbsp;&#8627; '
      html <<   collection.title
      html << '</h1>'
    else
      html << '<h1 class="dl-title">'
      html <<   collection.title
      html << '</h1>'
    end
    raw(html.string)
  end

  def effective_collection_access_url(collection)
    if collection.published_in_dls
      return collection_items_path(collection)
    elsif collection.public_in_medusa and collection.access_url and
        collection.access_url.length > 0
      return collection.access_url
    end
    nil
  end

  def repository_link(collection)
    begin
      title = collection.medusa_repository.title
      url = Configuration.instance.metadata_gateway_url +
          "/collections?fq%5B%5D=local_facet_repository%3A" +
        CGI.escape(title)
      return link_to(title, url)
    rescue IOError
      return ""
    end
  end

end

app/views/collections/_description.html.haml
.text-center.dl-browse-buttons
  - if @uofi_user
    - if @show_browse_tree_button
      = link_to(collection_tree_path(@collection),
                class: 'btn btn-lg btn-outline-primary') do
        Browse Collection
        = icon_for(@collection)
    - elsif @collection.published_in_dls 
      -# If the collection contains only one item, link straight to it.
      - if @num_public_objects == 1
        - link_target = item_path(@collection.items.first)
      - else
        - link_target = collection_items_path(@collection)
      = link_to(link_target,
                class: 'btn btn-lg btn-outline-primary',
                target: @collection.published_in_dls ? '' : '_blank') do
        = number_with_delimiter(@num_public_objects)
        = 'Item'.pluralize(@num_public_objects)
        = icon_for(Item)
    - elsif @collection.access_url.present?
      = link_to(@collection.access_url,
                class: 'btn btn-lg btn-outline-primary',
                target: @collection.published_in_dls ? '' : '_blank') do
        View Items
        = icon_for(Item)
  - if @collection.physical_collection_url.present?
    = link_to(@collection.physical_collection_url,
              class: 'btn btn-lg btn-outline-primary',
              target: '_blank',
              'aria-label': 'Full Collection Description, opens new window',
              data: {toggle: 'tooltip', placement: 'right'},
              title: 'Opens new window') do 
      = 'Full Collection Description'
      %i.fa.fa-external-link-alt

- unless @uofi_user
  .alert.alert-info
    Due to access restrictions, this collection is only available to
    authenticated on-campus users at the University of Illinois at Urbana-Champaign.

#dl-description
  = raw(@collection.description_html) || simple_format(auto_link(@collection.description))

- if @collection.free_form? && @uofi_user
  .alert.alert-info
    This collection is managed by the #{@collection.medusa_repository.title}
    and does not feature precise descriptive information for each item. Discover
    its contents by #{link_to 'browsing', collection_tree_path(@collection)}
    the folders and files. For more information, contact an archivist at
    = succeed "." do
      %a{href: "mailto:#{@collection.medusa_repository.email}"}= @collection.medusa_repository.email

app/views/collections/show.html.haml
- provide :title, @collection.title
- provide :body_id, 'collections_show'
- provide :active_nav, 'collections'
= breadcrumb(collection: @collection)

%form.form-inline.float-right{action: "#{collection_items_path(@collection)}",
                              method: "get"}
  .input-group
    - if @collection.published_in_dls && @uofi_user
      .input-group-prepend
        %span.input-group-text
          %i.fa.fa-search
      = search_field_tag :q,
                         params[:q],
                         class: 'form-control',
                         placeholder: 'Search This Collection'
    .input-group-append
      %button.btn.btn-light.dropdown-toggle{"aria-expanded": "false",
                                            "aria-haspopup": "true",
                                            "data-toggle": "dropdown",
                                            type: "button"}
        %i.fa.fa-eye
        View
        %span.caret
      .dropdown-menu.dropdown-menu-right
        - if @uofi_user
          = link_to collection_tree_path(@collection),
                    target: '_blank',
                    class: 'dropdown-item' do
            %i.fa.fa-folder-open 
            Browse Collection
          .dropdown-divider{role: "separator"}
          = link_to @permitted_params.merge(format: :json),
                    target: '_blank',
                    class: 'dropdown-item' do
            %i.fa.fa-code
             JSON
          = link_to collection_iiif_presentation_path(@collection),
                    target: '_blank',
                    class: 'dropdown-item' do
            %i.fa.fa-code
             IIIF Representation
          .dropdown-divider{role: "separator"} 
        = link_to admin_collection_path(@collection),
                  target: '_blank',
                  class: 'dropdown-item' do
          %i.fa.fa-lock
            Admin View

%h1= collection_page_title(@collection)

.row
  .col-sm-6.col-md-7.col-lg-8
    = render partial: 'description'
  .col-sm-6.col-md-5.col-lg-4
    .dl-main-image
      - if @representative_item
        - if @uofi_user
          = link_to @representative_item do
            = thumbnail_tag(@collection, size: 512)
          = link_to @representative_item, class: 'dl-title' do
            - if @representative_item.parent
              = @representative_item.parent.title
              —
            = @representative_item.title
        - else
          = thumbnail_tag(@collection, size: 512)
          = @representative_item.title
      - else
        = thumbnail_tag(@collection, size: 512)

- if @children.count > 0
  %hr/
  %h2
    Subcollections
    %small
      %span.badge.badge-pill.badge-secondary= @children.count
  .dl-cards
    = entities_as_cards(@children)

.text-center
  - mailto = curator_mailto(@collection)
  - if mailto
    = link_to mailto, class: 'btn btn-light' do
      %i.fa.fa-envelope
      Email Curator About This Collection

app/views/collections/unauthorized.html.haml
- provide :title, @collection.title
- provide :body_id, 'collections_show'
- provide :active_nav, 'collections'

- if current_user&.medusa_user?
  .btn-group.float-right{role: "group"}
    .btn-group{role: "group"}
      %button.btn.btn-light.dropdown-toggle{"aria-expanded": "false",
                                            "aria-haspopup": "true",
                                            "data-toggle": "dropdown",
                                            type: "button"}
        %i.fa.fa-eye
        View
        %span.caret
      .dropdown-menu.dropdown-menu-right{role: "menu"}
        = link_to admin_collection_path(@collection),
                  target: '_blank',
                  class: 'dropdown-item' do
          %i.fa.fa-lock
            Admin View
  %h1= collection_page_title(@collection)

.alert.alert-danger
  You are not authorized to access this collection.

app/views/collections/unpublished.html.haml
- provide :title, @collection.title
- provide :body_id, 'collections_show'
- provide :active_nav, 'collections'

= breadcrumb(collection: @collection)

.alert.alert-info This collection is unpublished.

.btn-group.float-right{role: "group"}
  .btn-group
    %button.btn.btn-light.dropdown-toggle{"aria-expanded": "false",
                                          "aria-haspopup": "true",
                                          "data-toggle": "dropdown",
                                          type: "button"}
      %i.fa.fa-eye
      View
      %span.caret
    %ul.dropdown-menu.dropdown-menu-right{role: "menu"}
      %li
        = link_to admin_collection_path(@collection), target: '_blank', class: 'dropdown-item' do
          %i.fa.fa-lock
            Admin View

%h1= collection_page_title(@collection)