config/routes.rb
            constraints: lambda { |request| request.xhr? }
      match '/edit-email-watchers', to: 'collections#edit_email_watchers', via: :get,
            constraints: lambda { |request| request.xhr? }
      match '/edit-info', to: 'collections#edit_info', via: :get,
            constraints: lambda { |request| request.xhr? }
      match '/edit-representation', to: 'collections#edit_representation', via: :get,
            constraints: lambda { |request| request.xhr? }
      resources :item_sets, except: :index do
        match '/all-items', to: 'item_sets#remove_all_items', via: :delete , as: "remove_all_items"
        match '/items', to: 'item_sets#items', via: :get, as: "items"
        match '/items', to: 'item_sets#remove_items', via: :delete, as: "remove_items"
      end
      match '/items/edit', to: 'items#edit_all', via: :get
      match '/items/enable-full-text-search', to: 'items#enable_full_text_search',
            via: :patch
      match '/items/disable-full-text-search', to: 'items#disable_full_text_search',
            via: :patch
      match '/items', to: 'collections#delete_items', via: :delete,
            as: 'delete_items'
      match '/items/publish', to: 'items#publish', via: :patch
      match '/items/run-ocr', to: 'items#run_ocr', via: :patch
      match '/items/unpublish', to: 'items#unpublish', via: :patch
      match '/items/update', to: 'items#update_all', via: :post
      resources :items, except: :edit do
        match '/edit-access', to: 'items#edit_access', via: :get,
              constraints: lambda { |request| request.xhr? }
        match '/edit-info', to: 'items#edit_info', via: :get,
              constraints: lambda { |request| request.xhr? }
        match '/edit-metadata', to: 'items#edit_metadata', via: :get,
              constraints: lambda { |request| request.xhr? }
        match '/edit-representation', to: 'items#edit_representation', via: :get,
              constraints: lambda { |request| request.xhr? }
        match '/publicize-child-binaries', to: 'items#publicize_child_binaries',
              via: :post
        match '/purge-cached-images', to: 'items#purge_cached_images',
              via: :post
        match '/run-ocr', to: 'items#run_ocr', via: :patch
        match '/unpublicize-child-binaries', to: 'items#unpublicize_child_binaries',
              via: :post
      end
      match '/items/add-items-to-item-set', to: 'items#add_items_to_item_set',
            via: :post
      match '/items/add-query-to-item-set', to: 'items#add_query_to_item_set',
            via: :post
      match '/items/import', to: 'items#import', via: :post
      match '/items/import-embedded-file-metadata',
            to: 'items#import_embedded_file_metadata', via: :post
      match '/items/batch-change-metadata', to: 'items#batch_change_metadata',
            via: :post
      match '/items/migrate-metadata', to: 'items#migrate_metadata', via: :post
      match '/items/replace-metadata', to: 'items#replace_metadata', via: :post
      match '/items/sync', to: 'items#sync', via: :post
      match '/purge-cached-images', to: 'collections#purge_cached_images',
            via: :post
      match '/statistics', to: 'collections#statistics', via: :get
      match '/unwatch', to: 'collections#unwatch', via: :patch
      match '/watch', to: 'collections#watch', via: :patch
    end
    resources :elements, param: :name do
      match '/usages', to: 'elements#usages', via: :get
    end
    match '/elements/import', to: 'elements#import', via: :post,
          as: 'elements_import'
    resources :host_groups
    resources :metadata_profile_elements,
              only: [:create, :update, :destroy, :edit]
    resources :metadata_profiles, path: 'metadata-profiles' do
      match '/clone', to: 'metadata_profiles#clone', via: :patch, as: 'clone'
      match '/delete-elements', to: 'metadata_profiles#delete_elements',
            via: :post, as: 'delete_elements'
      match '/reindex-items', to: 'metadata_profiles#reindex_items',
            via: :post, as: 'reindex_items'
    end
    match '/metadata-profiles/import', to: 'metadata_profiles#import',
          via: :post, as: 'metadata_profile_import'
    match '/settings', to: 'settings#index', via: :get
    match '/settings', to: 'settings#update', via: :patch
    match '/statistics', to: 'statistics#index', via: :get
    resources :tasks
    resources :users, param: :username, except: [:edit, :update] do
      match '/reset-api-key', to: 'users#reset_api_key', via: :post, as: 'reset_api_key'
    end
    resources :vocabularies do
      resources :vocabulary_terms, path: "terms"
      match '/delete-vocabulary-terms',
            to: 'vocabularies#delete_vocabulary_terms',
            via: :post, as: 'delete_vocabulary_terms'
    end
    match '/vocabularies/import', to: 'vocabularies#import', via: :post,
          as: 'vocabulary_import'
  end

  ############################ REST API routes ##############################

  namespace :api do
    root 'landing#index'
    resources :collections, only: [:index, :show, :update] do
      resources :items, only: :index
    end
    resources :items, only: [:index, :show, :destroy]
    match '/items/:id', to: 'items#update', via: :put
  end

  namespace :harvest do
    root 'harvest#index'
    resources :agents, only: :show, defaults: { format: :json }
    resources :collections, only: :show, defaults: { format: :json }
    resources :items, only: :show, defaults: { format: :json }
  end

  ############# Redirects from images.library.uiuc/illinois.edu #############

  match '/projects/:alias', to: 'collections#show_contentdm', via: :get
  match '/projects/:alias/*glob', to: 'collections#show_contentdm', via: :get

  ######################## CONTENTdm v4/5 redirects #########################

  # Reference URLs
  match '/u',
        to: 'contentdm#v4_reference_url', via: :all
  # Single-item URLs
  match '/cdm4/item_viewer.php',
        to: 'contentdm#v4_item', via: :all
  # Compound object URLs
  match '/cdm4/document.php',
        to: 'contentdm#v4_item', via: :all
  # Collection pages
  match '/cdm4/browse.php',
        to: 'contentdm#v4_collection', via: :all
  # Search results pages
  match '/cdm4/results.php',
        to: 'contentdm#v4_collection_items', via: :all
  match '/cdm4/search.php',
        to: redirect('/', status: 301), via: :all
  # OAI-PMH
  match '/cgi-bin/oai.exe',
        to: redirect('/oai-pmh', status: 301), via: :all
  match '/cgi-bin/oai2.exe',
        to: redirect('/oai-pmh', status: 301), via: :all
  # Admin
  match '/cgi-bin/admin/start.exe',
        to: redirect('/admin', status: 301), via: :all
  # Other pages
  match '/cdm4/about.php',
        to: redirect('/collections', status: 301), via: :all
  match '/cdm4/favorites.php',
        to: redirect('/', status: 301), via: :all
  match '/cdm4/help.php',
        to: redirect('/', status: 301), via: :all

  ######################### CONTENTdm v6 redirects ##########################

  # Reference URLs
  match '/cdm/ref/collection/:alias/:pointer',
        to: 'contentdm#v6_item', via: :all
  match '/cdm/ref/collection/:alias/id/:pointer',
        to: 'contentdm#v6_item', via: :all
  # Single-item URLs
  match '/cdm/singleitem/collection/:alias/id/:pointer',
        to: 'contentdm#v6_item', via: :all
  match '/cdm/singleitem/collection/:alias/id/:pointer/rec/:noop',
        to: 'contentdm#v6_item', via: :all
  # Compound object URLs
  match '/cdm/compoundobject/collection/:alias/id/:pointer',
        to: 'contentdm#v6_item', via: :all
  match '/cdm/compoundobject/collection/:alias/id/:pointer/rec/:noop',
        to: 'contentdm#v6_item', via: :all
  match '/cdm/compoundobject/collection/:alias/id/:pointer/show/:noop1/rec/:noop2',
        to: 'contentdm#v6_item', via: :all
  # Collection pages
  match '/cdm/landingpage/collection/:alias',
        to: 'contentdm#v6_collection', via: :all
  match '/cdm/about/collection/:alias',
        to: 'contentdm#v6_collection', via: :all
  # Search results pages
  match '/cdm/search',
        to: redirect('/items', status: 301), via: :all
  match '/cdm/search/collection/:alias',
        to: 'contentdm#v6_collection_items', via: :all
  match '/cdm/search/collection/:alias/order/:order/ad/:ad',
        to: 'contentdm#v6_collection_items', via: :all
  match '/cdm/search/collection/:alias/searchterm/:term/mode/:mode/page/:page',
        to: 'contentdm#v6_collection_items', via: :all
  match '/cdm/search/collection/:alias/searchterm/:term/mode/:mode/order/:order',
        to: 'contentdm#v6_collection_items', via: :all
  match '/cdm/search/collection/:alias/searchterm/:term/field/:field/mode/:mode/conn/:conn/order/:order',
        to: 'contentdm#v6_collection_items', via: :all
  match '/cdm/search/collection/:alias/searchterm/:term/field/:field/mode/:mode/conn/:conn/order/:order/ad/:ad',
        to: 'contentdm#v6_collection_items', via: :all
  match '/cdm/search/collection/:alias/searchterm/:term/field/:field/mode/:mode/conn/:conn/order/:order/page/:page',
        to: 'contentdm#v6_collection_items', via: :all
  match '/cdm/search/searchterm/:term',
        to: 'contentdm#v6_search_results', via: :all
  match '/cdm/search/searchterm/:term/mode/:mode',
        to: 'contentdm#v6_search_results', via: :all
  match '/cdm/search/searchterm/:term/mode/:mode/page/:page',
        to: 'contentdm#v6_search_results', via: :all
  match '/cdm/search/searchterm/:term/mode/:mode/order/:order',
        to: 'contentdm#v6_search_results', via: :all
  match '/cdm/search/searchterm/:term/mode/:mode/order/:order/ad/:ad',
        to: 'contentdm#v6_search_results', via: :all
  match '/cdm/search/searchterm/:term/mode/:mode/order/:order/ad/:ad/page/:page',
        to: 'contentdm#v6_search_results', via: :all
  match '/cdm/search/searchterm/:term/mode/:mode/order/:order/page/:page',
        to: 'contentdm#v6_search_results', via: :all
  match '/cdm/search/searchterm/:term/order/:order',

app/controllers/admin/elements_controller.rb
# frozen_string_literal: true

module Admin

  class ElementsController < ControlPanelController

    include ActionController::Live

    class ImportMode
      MERGE   = 'merge'
      REPLACE = 'replace'
    end

    before_action :set_element, except: [:create, :import, :index]
    before_action :authorize_element, except: [:create, :import, :index]

    ##
    # XHR only
    #
    def create
      @element = Element.new(permitted_params)
      authorize(@element)
      begin
        @element.save!
      rescue ActiveRecord::RecordInvalid
        response.headers['X-Kumquat-Result'] = 'error'
        render partial: 'shared/validation_messages',
               locals: { entity: @element }
      rescue => e
        handle_error(e)
        keep_flash
        render 'admin/shared/reload'
      else
        response.headers['X-Kumquat-Result'] = 'success'
        flash['success'] = "Element \"#{@element.name}\" created."
        keep_flash
        render 'admin/shared/reload'
      end
    end

    def destroy
      @element.destroy!
    rescue => e
      handle_error(e)
    else
      flash['success'] = "Element \"#{@element.name}\" deleted."
    ensure
      redirect_back fallback_location: admin_elements_path
    end

    ##
    # XHR only
    #
    def edit
      render partial: 'admin/elements/form',
             locals: { element: @element }
    end

    ##
    # Responds to POST /admin/elements/import
    #
    def import
      authorize(Element)
      raise 'No elements specified.' if params[:elements].blank?
      json   = params[:elements].read.force_encoding('UTF-8')
      struct = JSON.parse(json)
      ActiveRecord::Base.transaction do
        if params[:import_mode] == ImportMode::REPLACE
          Element.delete_all # skip callbacks & validation
        end
        struct.each do |hash|
          e = Element.find_by_name(hash['name'])
          if e
            e.update_from_json_struct(hash)
          else
            Element.from_json_struct(hash).save!
          end
        end
      end
    rescue => e
      handle_error(e)
      redirect_to admin_elements_path
    else
      flash['success'] = "#{struct.length} elements created or updated."
      redirect_to admin_elements_path
    end

    ##
    # Responds to GET /elements
    #
    def index
      authorize(Element)
      respond_to do |format|
        format.html do
          sql = 'SELECT elements.id, elements.name, elements.description,
              (SELECT COUNT(metadata_profile_elements.name)
                FROM metadata_profile_elements
                WHERE metadata_profile_elements.name = elements.name) AS metadata_profile_count,
              (SELECT COUNT(entity_elements.name)
                FROM entity_elements
                WHERE entity_elements.name = elements.name) AS entity_count
              FROM elements
              GROUP BY elements.id, elements.name
              ORDER BY elements.name;'
          @elements    = ActiveRecord::Base.connection.exec_query(sql)
          @new_element = Element.new
        end
        format.json do
          @elements = Element.all.order(:name)
          headers['Content-Disposition'] = 'attachment; filename=elements.json'
          render plain: JSON.pretty_generate(@elements.as_json)
        end
      end
    end

    ##
    # Responds to GET /admin/elements/:name
    #
    def show
    end

    ##
    # XHR only
    #
    def update
      @element.update!(permitted_params)
    rescue ActiveRecord::RecordInvalid
      response.headers['X-Kumquat-Result'] = 'error'
      render partial: 'shared/validation_messages',
             locals:  { entity: @element }
    rescue => e
      handle_error(e)
      keep_flash
      render 'admin/shared/reload'
    else
      response.headers['X-Kumquat-Result'] = 'success'
      flash['success'] = "Element \"#{@element.name}\" updated."
      keep_flash
      render 'admin/shared/reload'
    end

    ##
    # Responds to GET /admin/elements/:name/usages with a TSV-format list of
    # all usages of a given element by all items.
    #
    def usages
      response.headers['Content-Type']        = 'text/tab-separated-values; charset=utf-8'
      response.headers['Content-Disposition'] = "attachment;filename=#{@element.name}.tsv"

      response.stream.write "collection_id\titem_id\telement_name\telement_value\telement_uri" +
                ItemTsvExporter::LINE_BREAK
      @element.usages.each do |row|
        response.stream.write row.values.join("\t")
        response.stream.write ItemTsvExporter::LINE_BREAK
      end
    ensure
      response.stream.close
    end


    private

    def authorize_element
      @element ? authorize(@element) : skip_authorization
    end

    def permitted_params
      params.require(:element).permit(:description, :name)
    end

    def set_element
      @element = Element.find_by_name(params[:name] || params[:element_name])
      raise ActiveRecord::RecordNotFound unless @element
    end

  end

end

app/views/admin/elements/_add_modal.html.haml
-# Add-element modal

#dl-add-element-modal.modal.fade{"aria-labelledby": "dl-add-element-modal-label",
                                 role: "dialog",
                                 tabindex: "-1"}
  .modal-dialog.modal-dialog-centered{role: "document"}
    .modal-content
      .modal-header
        %h4#dl-add-element-modal-label.modal-title Add Element
        %button.close{"aria-label": "Close",
                      "data-dismiss": "modal",
                      type: "button"}
          %span{"aria-hidden": "true"} ×
      .modal-body
        = render partial: 'form', locals: { element: @new_element }

app/views/admin/elements/_edit_modal.html.haml
-# Edit-element modal

#dl-edit-element-modal.modal.fade{"aria-labelledby": "dl-edit-element-modal-label",
                                  role: "dialog",
                                  tabindex: "-1"}
  .modal-dialog.modal-dialog-centered{role: "document"}
    .modal-content
      .modal-header
        %h4#dl-edit-element-modal-label.modal-title Edit Element
        %button.close{"aria-label": "Close",
                      "data-dismiss": "modal",
                      type: "button"}
          %span{"aria-hidden": "true"} ×
      .modal-body
        -# will be populated via XHR

app/views/admin/elements/_form.html.haml
-# @param element [Element]

= form_for([:admin, element], remote: true) do |f|
  .dl-error-messages
    -# populated via ajax by shared/_validation_messages.js.erb
  .form-group
    = f.label :name
    - if f.object.new_record?
      = f.text_field :name, class: 'form-control'
    - else
      %br/
      = element.name
  .form-group
    = f.label :description
    = f.text_area :description, class: 'form-control'
  .clearfix
    .float-right
      %button.btn.btn-light{"data-dismiss": "modal", type: "button"} Cancel
      = f.submit(f.object.new_record? ? 'Create Element' : 'Edit Element',
                 class: 'btn btn-primary')

app/views/admin/elements/_import_modal.html.haml
-# Import-elements modal

#dl-import-modal.modal.fade{"aria-labelledby": "dl-import-modal-label",
                            role: "dialog",
                            tabindex: "-1"}
  .modal-dialog.modal-dialog-centered{role: "document"}
    .modal-content
      = form_tag(admin_elements_import_path(format: :json),
                 { multipart: true }) do
        .modal-header
          %h4#dl-import-modal-label.modal-title Import Elements
          %button.close{"aria-label": "Close", "data-dismiss": "modal", type: "button"}
            %span{"aria-hidden": "true"} ×
        .modal-body
          = file_field_tag('elements')
          %hr/
          .form-group
            .radio
              %label
                = radio_button_tag('import_mode',
                                   Admin::ElementsController::ImportMode::MERGE, true,
                                   'aria-described-by': 'dl-merge-help')
                Merge
              %span#dl-merge-help.form-text.text-muted
                Create any new elements, and update existing elements, but don't
                delete any elements.
          .form-group
            .radio
              %label
                = radio_button_tag('import_mode',
                                   Admin::ElementsController::ImportMode::REPLACE, false,
                                   'aria-described-by': 'dl-only-create-help')
                Replace
              %span#dl-only-create-help.form-text.text-muted
                Replace the current list of elements with the ones being imported.
        .modal-footer
          %button.btn.btn-light{"data-dismiss": "modal", type: "button"} Cancel
          %button.btn.btn-primary{type: "submit"} Import

app/views/admin/elements/index.html.haml
- provide :title, 'Elements'
- provide :body_id, 'elements'
- provide :active_nav, 'metadata'

= admin_breadcrumb({ label: 'Home', url: admin_root_path },
                   { label: 'Elements' })

.btn-group.float-right{role: "group"}
  - if policy(Element).new?
    -# Add Element button
    %button.btn.btn-light{"data-target": "#dl-add-element-modal",
                          "data-toggle": "modal",
                          type:          "button"}
      %span.fa.fa-plus
      Add Element
    -# Import button
    %button.btn.btn-light{"data-target": "#dl-import-modal",
                          "data-toggle": "modal",
                          type:          "button"}
      %i.fa.fa-upload
      Import&hellip;
  -# Export button
  = link_to admin_elements_path(format: 'json'), role: 'button', class: 'btn btn-light' do
    %i.fa.fa-download
    Export

%h1 Elements

%table.table.table-striped
  %thead
    %tr
      %th{style: "width: 1px"}
      %th Element
      %th Description
      %th Metadata Profile Occurrences
      %th Entity Occurrences
  %tbody
    - @elements.each do |row|
      %tr
        %td{style: "white-space: nowrap"}
          .btn-group
            -# TODO: this is unfortunate for performance
            - if policy(Element.find_by_name(row['name'])).edit?
              %button.btn.btn-light.btn-sm.dl-edit-element{"data-element-id": "#{row['name']}",
                                                           "data-target":     "#dl-edit-element-modal",
                                                           "data-toggle":     "modal",
                                                           type:              "button"}
                %i.fas.fa-pencil-alt
                Edit
              - if row['entity_count'].to_i > 0
                = link_to '#', class: 'btn btn-danger btn-sm', disabled: true do
                  %i.fa.fa-trash
                  Delete
              - else
                = button_to admin_element_path(row['name']),
                            class:  'btn btn-danger btn-sm',
                            method: :delete,
                            data:   { confirm: 'Are you sure you want to delete this element?' } do
                  %i.fa.fa-trash
                  Delete
        %td{style: "white-space: nowrap"}
          %code= link_to row['name'], admin_element_path(row['name'])
        %td= row['description']
        %td= number_with_delimiter(row['metadata_profile_count'])
        %td= number_with_delimiter(row['entity_count'])

= render partial: 'admin/elements/add_modal'
= render partial: 'admin/elements/edit_modal'
= render partial: 'admin/elements/import_modal'

app/views/admin/elements/show.html.haml
- provide :title, @element.name
- provide :body_id, 'admin_element_show'
- provide :active_nav, 'metadata'

= admin_breadcrumb({ label: 'Home', url: admin_root_path },
                   { label: 'Elements', url: admin_elements_path },
                   { label: @element.name })

.btn-group.float-right
  -# Export button
  = link_to admin_element_usages_path(@element), role: 'button', class: 'btn btn-light' do
    %i.fa.fa-download
    Export Usages as TSV

%h1= @element.name

- if @element.description.present?
  %p= @element.description