config/routes.rb
Rails.application.routes.draw do
  root 'landing#index'

  # Error routes that work in conjunction with
  # config.exceptions_app = self.routes.
  match '/404', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

  ######################### Public website routes ###########################

  resources :agents, only: :show do
    match '/items', to: 'agents#items', via: :get, as: 'items'
  end
  match '/auth/:provider/callback', to: 'sessions#create', via: [:get, :post],
        as: 'auth' # used by omniauth
  resources :binaries, only: :show do
    match '/object', to: 'binaries#object', via: :get
    match '/stream', to: 'binaries#stream', via: :get
  end
  match '/collections/iiif', to: 'collections#iiif_presentation_list',
        via: :get, as: 'collections_iiif_presentation_list',
        defaults: { format: :json }
  resources :collections, only: [:index, :show] do
    match 'items/treedata', to: 'items#tree_data', via: [:get, :post]
    match 'tree', to: 'items#tree', via: :get
    resources :items, only: :index
    # IIIF Presentation API 2.1 routes
    match '/iiif', to: 'collections#iiif_presentation', via: :get,
          as: 'iiif_presentation', defaults: { format: :json }
  end
  resources :downloads, only: :show, param: :key do
    match '/file', to: 'downloads#file', via: :get, as: 'file'
  end
  match '/health', to: 'health#index', via: :get
  resources :items, only: [:index, :show] do
    match '/treedata', to: 'items#item_tree_node', via: [:get, :post]
    match '/binaries/:filename', to: 'items#binary', via: :get, as: 'binary'
    match '/files', to: 'items#files', via: :get, as: 'files'
    # IIIF Presentation API 2.1 routes
    match '/annotation/:name', to: 'items#iiif_image_resource', via: :get,
          as: 'iiif_image_resource', defaults: { format: :json }
    match '/canvas/:id', to: 'items#iiif_canvas', via: :get, as: 'iiif_canvas',
          defaults: { format: :json }
    match '/layer/:name', to: 'items#iiif_layer', via: :get, as: 'iiif_layer',
          defaults: { format: :json }
    match '/annotation-list/:name', to: 'items#iiif_annotation_list', via: :get,
          as: 'iiif_annotation_list',
          defaults: { format: :json }
    match '/manifest', to: 'items#iiif_manifest', via: :get,
          as: 'iiif_manifest', defaults: { format: :json }
    match '/range/:name', to: 'items#iiif_range', via: :get, as: 'iiif_range',
          defaults: { format: :json }
    match '/sequence/:name', to: 'items#iiif_sequence', via: :get,
          as: 'iiif_sequence', defaults: { format: :json }
    # IIIF Search API routes
    match '/manifest/search', to: 'items#iiif_search', via: :get,
          as: 'iiif_search', defaults: { format: :json }
    # Wellcome Library API extension
    match '/xsequence/:name', to: 'items#iiif_media_sequence', via: :get,
          as: 'iiif_media_sequence', defaults: { format: :json }
  end
  match '/oai-pmh', to: 'oai_pmh#handle', via: %w(get post), as: 'oai_pmh'
  match '/oai-pmh/idhh', to: 'oai_pmh#handle', via: %w(get post), as: 'idhh_oai_pmh'
  match '/oai-pmh/primo', to: 'oai_pmh#handle', via: %w(get post), as: 'primo_oai_pmh'
  match '/search', to: redirect('/', status: 301), via: :all
  match '/signin', to: 'sessions#new', via: :get
  match '/signout', to: 'sessions#destroy', via: :delete

  ######################### Control Panel routes ###########################

  namespace :admin do
    root 'dashboard#index'

    resources :agents
    resources :agent_relation_types, except: :show,
              path: 'agent-relation-types'
    resources :agent_relations, except: [:index, :show], path: 'agent-relations'
    resources :agent_rules, except: :show, path: 'agent-rules'
    resources :agent_types, except: :show, path: 'agent-types'
    resources :binaries, only: :update do
      match '/edit-access', to: 'binaries#edit_access', via: :get
      match '/run-ocr', to: 'binaries#run_ocr', via: :patch
    end
    match '/collections/items', to: 'collections#items', via: :get
    match '/collections/sync', to: 'collections#sync', via: :patch,
          as: 'collections_sync'
    resources :collections, except: [:edit, :new, :create, :delete] do
      match '/edit-access', to: 'collections#edit_access', via: :get,
            constraints: lambda { |request| request.xhr? }
      match '/edit-email-watchers', to: 'collections#edit_email_watchers', via: :get,
            constraints: lambda { |request| request.xhr? }
      match '/edit-info', to: 'collections#edit_info', via: :get,
            constraints: lambda { |request| request.xhr? }
      match '/edit-representation', to: 'collections#edit_representation', via: :get,
            constraints: lambda { |request| request.xhr? }
      resources :item_sets, except: :index do
        match '/all-items', to: 'item_sets#remove_all_items', via: :delete , as: "remove_all_items"
        match '/items', to: 'item_sets#items', via: :get, as: "items"
        match '/items', to: 'item_sets#remove_items', via: :delete, as: "remove_items"
      end
      match '/items/edit', to: 'items#edit_all', via: :get
      match '/items/enable-full-text-search', to: 'items#enable_full_text_search',
            via: :patch
      match '/items/disable-full-text-search', to: 'items#disable_full_text_search',
            via: :patch
      match '/items', to: 'collections#delete_items', via: :delete,
            as: 'delete_items'
      match '/items/publish', to: 'items#publish', via: :patch
      match '/items/run-ocr', to: 'items#run_ocr', via: :patch
      match '/items/unpublish', to: 'items#unpublish', via: :patch
      match '/items/update', to: 'items#update_all', via: :post
      resources :items, except: :edit do
        match '/edit-access', to: 'items#edit_access', via: :get,
              constraints: lambda { |request| request.xhr? }
        match '/edit-info', to: 'items#edit_info', via: :get,
              constraints: lambda { |request| request.xhr? }
        match '/edit-metadata', to: 'items#edit_metadata', via: :get,
              constraints: lambda { |request| request.xhr? }
        match '/edit-representation', to: 'items#edit_representation', via: :get,
              constraints: lambda { |request| request.xhr? }
        match '/publicize-child-binaries', to: 'items#publicize_child_binaries',
              via: :post
        match '/purge-cached-images', to: 'items#purge_cached_images',
              via: :post
        match '/run-ocr', to: 'items#run_ocr', via: :patch
        match '/unpublicize-child-binaries', to: 'items#unpublicize_child_binaries',
              via: :post
      end
      match '/items/add-items-to-item-set', to: 'items#add_items_to_item_set',
            via: :post
      match '/items/add-query-to-item-set', to: 'items#add_query_to_item_set',
            via: :post
      match '/items/import', to: 'items#import', via: :post
      match '/items/import-embedded-file-metadata',
            to: 'items#import_embedded_file_metadata', via: :post
      match '/items/batch-change-metadata', to: 'items#batch_change_metadata',
            via: :post
      match '/items/migrate-metadata', to: 'items#migrate_metadata', via: :post
      match '/items/replace-metadata', to: 'items#replace_metadata', via: :post
      match '/items/sync', to: 'items#sync', via: :post
      match '/purge-cached-images', to: 'collections#purge_cached_images',
            via: :post
      match '/statistics', to: 'collections#statistics', via: :get
      match '/unwatch', to: 'collections#unwatch', via: :patch
      match '/watch', to: 'collections#watch', via: :patch
    end
    resources :elements, param: :name do
      match '/usages', to: 'elements#usages', via: :get
    end
    match '/elements/import', to: 'elements#import', via: :post,
          as: 'elements_import'
    resources :host_groups
    resources :metadata_profile_elements,
              only: [:create, :update, :destroy, :edit]
    resources :metadata_profiles, path: 'metadata-profiles' do
      match '/clone', to: 'metadata_profiles#clone', via: :patch, as: 'clone'
      match '/delete-elements', to: 'metadata_profiles#delete_elements',
            via: :post, as: 'delete_elements'
      match '/reindex-items', to: 'metadata_profiles#reindex_items',
            via: :post, as: 'reindex_items'
    end
    match '/metadata-profiles/import', to: 'metadata_profiles#import',
          via: :post, as: 'metadata_profile_import'
    match '/settings', to: 'settings#index', via: :get
    match '/settings', to: 'settings#update', via: :patch
    match '/statistics', to: 'statistics#index', via: :get
    resources :tasks
    resources :users, param: :username, except: [:edit, :update] do
      match '/reset-api-key', to: 'users#reset_api_key', via: :post, as: 'reset_api_key'
    end
    resources :vocabularies do
      resources :vocabulary_terms, path: "terms"
      match '/delete-vocabulary-terms',
            to: 'vocabularies#delete_vocabulary_terms',
            via: :post, as: 'delete_vocabulary_terms'
    end
    match '/vocabularies/import', to: 'vocabularies#import', via: :post,
          as: 'vocabulary_import'
  end

  ############################ REST API routes ##############################

  namespace :api do
    root 'landing#index'
    resources :collections, only: [:index, :show, :update] do
      resources :items, only: :index
    end
    resources :items, only: [:index, :show, :destroy]
    match '/items/:id', to: 'items#update', via: :put
  end

  namespace :harvest do
    root 'harvest#index'
    resources :agents, only: :show, defaults: { format: :json }
    resources :collections, only: :show, defaults: { format: :json }
    resources :items, only: :show, defaults: { format: :json }
  end

  ############# Redirects from images.library.uiuc/illinois.edu #############

  match '/projects/:alias', to: 'collections#show_contentdm', via: :get

app/views/layouts/admin/_header.html.haml
%nav.navbar.navbar-expand-md.navbar-dark
  %button.navbar-toggler{"aria-controls": "dl-navbar1-collapse",
                         "aria-expanded": "false",
                         "aria-label": "Toggle navigation",
                         "data-target": "#dl-navbar1-collapse",
                         "data-toggle": "collapse",
                         type: "button"}
    %span.navbar-toggler-icon
  #dl-navbar1-collapse.collapse.navbar-collapse
    %ul.navbar-nav
      %li.nav-item
        = link_to 'Collection Registry',
                  Configuration.instance.medusa_url,
                  class: 'nav-link'
      %li.nav-item.active
        = link_to 'Digital Library', '#', class: 'nav-link'
      %li.nav-item
        = link_to 'Metadata Gateway',
                  Configuration.instance.metadata_gateway_url + '/admin',
                  class: 'nav-link'
%nav.navbar.navbar-expand-md.navbar-dark.bg-dark
  = link_to admin_root_path, class: 'navbar-brand' do
    %i.fas.fa-tachometer-alt
  %button.navbar-toggler{"aria-controls": "dl-navbar2-collapse",
                         "aria-expanded": "false",
                         "aria-label": "Toggle navigation",
                         "data-target": "#dl-navbar2-collapse",
                         "data-toggle": "collapse",
                         type: "button"}
    %span.navbar-toggler-icon
  #dl-navbar2-collapse.collapse.navbar-collapse
    %ul.navbar-nav
      - if policy(Collection).index?
        %li.nav-item
          = link_to 'Collections', admin_collections_path, class: 'nav-link'

      -# Metadata menu
      - show_elements             = policy(Element).index?
      - show_vocabularies         = policy(Vocabulary).index?
      - show_metadata_profiles    = policy(MetadataProfile).index?
      - show_agents               = policy(Agent).index?
      - show_agent_relation_types = policy(AgentRelationType).index?
      - show_agent_rules          = policy(AgentRule).index?
      - show_agent_types          = policy(AgentType).index?
      - if show_elements || show_vocabularies || show_metadata_profiles || show_agents || show_agent_relation_types || show_agent_rules || show_agent_types
        %li#metadata-nav.nav-item.dropdown
          %a.nav-link.dropdown-toggle{"data-toggle": "dropdown", href: "#"}
            Metadata
            %b.caret
          .dropdown-menu
            - if show_elements
              = link_to 'Elements', admin_elements_path, class: 'dropdown-item'
            - if show_vocabularies
              = link_to 'Vocabularies', admin_vocabularies_path, class: 'dropdown-item'
            - if show_metadata_profiles
              = link_to 'Metadata Profiles', admin_metadata_profiles_path, class: 'dropdown-item'
            - if (show_elements || show_vocabularies || show_metadata_profiles) && (show_agents || show_agent_relation_types || show_agent_rules || show_agent_types)
              .dropdown-divider
            - if show_agents
              = link_to 'Agents', admin_agents_path, class: 'dropdown-item'
            - if show_agent_relation_types
              = link_to 'Agent Relation Types', admin_agent_relation_types_path, class: 'dropdown-item'
            - if show_agent_rules
              = link_to 'Agent Rules', admin_agent_rules_path, class: 'dropdown-item'
            - if show_agent_types
              = link_to 'Agent Types', admin_agent_types_path, class: 'dropdown-item'

      -# Access menu
      - show_users       = policy(User).index?
      - show_host_groups = policy(HostGroup).index?
      %li#access-nav.nav-item.dropdown
        %a.nav-link.dropdown-toggle{"data-toggle": "dropdown", href: "#"}
          Access
          %b.caret
        .dropdown-menu
          - if show_users
            = link_to 'Users', admin_users_path, class: 'dropdown-item'
          - if show_host_groups
            = link_to 'Host Groups', admin_host_groups_path, class: 'dropdown-item'

      -# Server menu
      - show_statistics  = policy(:statistic).index?
      - show_tasks       = policy(Task).index?
      - show_settings    = policy(Setting).index?
      %li#server-nav.nav-item.dropdown
        %a.nav-link.dropdown-toggle{"data-toggle": "dropdown", href: "#"}
          Server
          %b.caret
        .dropdown-menu
          = link_to 'Analytics', 'https://analytics.google.com/analytics/web/#/p383482182/reports/intelligenthome', class: 'dropdown-item'
          - if show_statistics
            = link_to 'Statistics', admin_statistics_path, class: 'dropdown-item'
          - if show_tasks
            = link_to 'Tasks', admin_tasks_path, class: 'dropdown-item'
          - if show_settings
            .dropdown-divider
            = link_to 'Settings', admin_settings_path, class: 'dropdown-item'

    .navbar-nav.ml-md-auto
      %ul.navbar-nav
        %li.nav-item
          %a.nav-link{href: "https://wiki.library.illinois.edu/scars/Production_Services/Illinois_Digital_Library/DLS",
                      target: "_blank"}
            %i.fa.fa-question-circle
        %li.nav-item.dropdown
          %a.dropdown-toggle.nav-link{"aria-expanded": "false",
                                      "aria-haspopup": "true",
                                      "data-toggle": "dropdown",
                                      href: "#"}
            %i.fas.fa-user{"aria-hidden": "true"}
            = current_user.username
            %b.caret
          .dropdown-menu.dropdown-menu-right{"aria-labelledby": "dl-user-menu-toggle"}
            = link_to 'My Account', admin_user_path(current_user), class: 'dropdown-item'
            = link_to 'Public Website', root_url, class: 'dropdown-item'
            .dropdown-divider
            = link_to 'OAI-PMH Endpoint (Generic)', oai_pmh_path, class: 'dropdown-item'
            = link_to 'OAI-PMH Endpoint (IDHH)', idhh_oai_pmh_path, class: 'dropdown-item'
            = link_to 'OAI-PMH Endpoint (Primo)', primo_oai_pmh_path, class: 'dropdown-item'
            .dropdown-divider
            = link_to 'Log Out', signout_path, method: 'delete', class: 'dropdown-item'

app/views/layouts/admin/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}
    %title
      #{yield(:title)} | UIUC Library Digital Special Collections Control Panel
    %meta{charset: "utf-8"}/
    %meta{content: "width=device-width, initial-scale=1", name: "viewport"}
    = csrf_meta_tags
    = stylesheet_link_tag 'admin/application', media: 'all'
    = javascript_include_tag 'admin/application'
    = content_for :head

  %body.dl-admin{id: yield(:body_id).present? ? raw(yield(:body_id)) : nil,
                 "data-nav": yield(:active_nav)}
    = hidden_field_tag('root_url', root_url)

    = render partial: 'layouts/admin/header'
    .container-fluid
      .page-content
        = flashes
        = yield
    %footer  
    = ajax_shade